# Generated by Django 3.2.9 on 2021-12-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Birth_Year', models.CharField(max_length=60)),
                ('Eye_Color', models.CharField(max_length=60)),
                ('Gender', models.CharField(max_length=60)),
                ('Height', models.IntegerField()),
            ],
        ),
    ]
